version: "3.0"

services:
  app:
    build: .
    container_name: mongoKumar
    ports: 
    - 4000:3000
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
